int assembleF(Token*);
int comma_remover(char*);
int char_chk(char);
void symbolF();
int Assembly_pass1(FILE*);
int Assembly_pass2(FILE*, FILE*);
symbolInfo* findSymbol(char*);
int findRegister(char*);
Assembly* tokenize_assembly(char*);
void symbolAdd(char*, int);
void addRecord(int, int);
void printRecord(FILE*);
void add_objL(Assembly*);
void print_objL(FILE*);
void print_obj(FILE*, Assembly*, int);
void free_objL();
void print_lst(FILE*, Assembly*, int, int);
void freeRecord();
void freeSymbol();
void freeAssembly();
